name: Docker Image Build and Push to Docker hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: $${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build -t tanvircse/docker-node-app -f 06NodeCI/dockerfile .
    - name: Docker image push to Docker hub
      run: docker push tanvircse/docker-node-app
