# .github/workflows/docker-build.yml

name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t tanvircse/docker-node-app -f 06NodeCI/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: docker push tanvircse/docker-node-app
